version: '3.8'

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5005:5005
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: no
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres-db

volumes:
  pgdata:
  pgadmin-data:
